name: ask

x-common-app-config: &common-app-config
  image: varlabz/ask:latest
  network_mode: host
  volumes:
    - ${HOME}/.config/ask:/root/.config/ask:ro
    - tmp:/tmp
  stdin_open: true

services:
  # example to run with chat browser UI. can use with any file from examples folder
  # usage: docker compose run --rm ask-chat
  ask-chat:
    <<: *common-app-config
    command: ["ask-duckduckgo", "--chat", "--no-native",]

  # example to run with terminal chat UI
  # usage: docker compose run -i --rm ask-tchat
  ask-tchat:
    <<: *common-app-config
    command: ["ask-duckduckgo", "--tchat",]

  # example for user's own app to run from local filesystem
  my-app:
    <<: *common-app-config
    volumes:
      - ${HOME}/.config/ask:/root/.config/ask:ro
      - tmp:/tmp
      - $PWD/:/app
    command: [your command and args here]

volumes:
  tmp:

