[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ask"
version = "0.1.1"
description = "ASK CLI/MCP"
authors = [
    { name = "varlabz", email = "varlabz@umdoze.com" }
]
dependencies = [
    "pydantic-ai[mcp]",
    "pyyaml"
]
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio"
]

[project.scripts]
cli = "cli_main:cli_main"
mcp = "mcp_main:mcp_main"
