[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ask"
version = "0.11.3"
description = "ASK CLI/MCP"
authors = [
    { name = "varlabz", email = "varlabz@umdoze.com" }
]
dependencies = [
    "pydantic-ai",
    "mcp[cli]",
    "pyyaml",
    "openai<=1.99.1", # temp
    "griffe>=1.7.3",
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.30.0",
    "typing-extensions>=4.12.2",
    "prompt-toolkit>=3.0.0",
    "streamlit>=1.49.1",
]
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio"
]

[project.scripts]
ask-cli = "cli_main:main"
ask-mcp = "mcp_main:main"

[tool.setuptools]
package-dir = {"" = "src"}
