[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ask"
version = "0.9.0"
description = "ASK CLI/MCP"
authors = [
    { name = "varlabz", email = "varlabz@umdoze.com" }
]
dependencies = [
    "pydantic-ai",
    "mcp[cli]",
    "pyyaml",
    "openai<=1.99.1", # temp
    "griffe>=1.7.3",
]
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio"
]

[project.scripts]
ask-cli = "cli_main:cli_main"
ask-mcp = "mcp_main:mcp_main"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["agent", "cli_main", "config", "mcp_client", "mcp_main", "model"]
